spring:
  # DB
  datasource:
    url: jdbc:h2:mem:movie_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: 'classpath:/db/changelog/db.changelog-master.xml'
  h2:
    console:
      enabled: true